ads:
  url_regex:
    - 'https?://\S+'
    - 'www\.[\w.-]+'
  phone_regex:
    # Allow spaces, parentheses and dots, e.g., +65 9123-4567 or (65) 9123 4567 or 65.9123.4567
    - '\b\+?\d[\d\s().-]{7,}\b'
  keywords:
    - 'promo'
    - 'discount'
    - '% off'
    - 'coupon'
    - 'call now'
    - 'dm us'
    - 'book via'
    - 'whatsapp'
    - 'telegram'
    - 'line id'
    - 'use code'

irrelevant:
  min_cosine_to_business: 0.1  # we'll sweep this next
  off_topic_keywords:
    restaurant:
      - 'iphone'
      - 'laptop'
      - 'headphones'
      - 'delivery app bug'
      - 'firmware'
      - 'graphics card'
    electronics:
      - 'latte'
      - 'croissant'
      - 'cappuccino'
      - 'pastry'
      - 'mocha'
    park:
      - 'pizza'
      - 'burger'
      - 'pasta'
      - 'wifi'
    spa:
      - 'pizza'
      - 'burger'
      - 'fries'
      - 'pasta'

rant_no_visit:
  positive_cues:
    - "haven't been"
    - 'never been'
    - "didn't try"
    - 'i heard'
    - 'people say'
    - 'someone told me'
  negation_window: 3
